import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layouts/navbar";
import Footer from "@/components/layouts/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Senayit Awoke Portfolio",
  description: "Generated by myself, Senayit Awoke",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* <body className="min-h-full w-full flex flex-col "> */}
      <body className="min-h-full w-full flex flex-col ">
        <NavBar />
        {/* <div className="h-20" /> */}
        {/* fix the flex grow */}
        <main className="min-h-screen p-6 pt-20 pb-18 md:px-18 md:pb-24  bg-linear-to-r from-zinc-950 via-slate-950 to-zinc-950 ">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
